name: Service container sample
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sue
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Migrate DB schema
        shell: bash
        run: |
          export PATH=$PATH:$GOPATH/bin
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
      
      - name: Get dependencies
        run: go get github.com/lib/pq
      
      - name: Run
        run: go run cmd/sample/main.go
