name: Service container sample
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    env:
      ENV: runner-job
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sue
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Migrate DB schema
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up -config=configs/dbconfig.yml -env=${ENV}
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
      
      - name: Run
        run: go run cmd/sample/main.go

  container-job:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14
    env:
      ENV: container-job
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sue
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2

      - name: Migrate DB schema
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up -config=configs/dbconfig.yml -env=${ENV}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      
      - name: Run
        run: go run cmd/sample/main.go

